[tool.poetry]
name = "fake_project"
version = "0.2.0-beta0"
description = ""
authors = ["britodfbr <britodfbr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
